#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnfG9V8k3OmKr7v10/mrjJ+rjbRBYJkXXDvmkjPqaNPQDjB1uCkt7y/lY0W0UUEPLy2kbcT2pUgm4iy+FbS5U2y5wi32x9GaTJ76fQqtcbcrlBqnmfUNfR1mFio32OU8YagfCJSPEQ48Krws6TneSKa8+BYKACZ/L+Xb3Udn3wGk9maQyW7jxmtHG5wHcZXGagG9+isrkS8Yy9/FwxY/KyEytvTnFlAxMYsXXF6/njuVT5CXv85B0JT7Cuc6uZY5mpTdeyp6dKHYi0rs4wQnBrnGZLeFP9C+kVoe1ZvfSa+468dsW7Kk3besU6kkzso53jP3cNVQaB+I8ikicUqQKB WebKey
    ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - apache2
  - curl
  - wget
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
write_files:
  - content: |
      <?php phpinfo(); ?>
    path: /var/www/html/info.php
    permissions: "0644"
  - content: |
      <?php
        $servername = "172.31.32.148";
        $username = "admin";
        $password = "password";
        $dbname = "mysql";
        $conn = new mysqli($servername, $username, $password, $dbname);
        if ($conn->connect_error) {
          die("Connection failed: " . $conn->connect_error);
        }
        $sql = "select Host, User from mysql.user;";
        $result = $conn->query($sql);
        while($row = $result->fetch_assoc()){
          echo($row["Host"] . " / " . $row["User"] . "<br />");
        }
      ?>
    path: /var/www/html/db.php
    permissions: "0644"
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
